[tool.poetry]
name = "pretraining"
version = "0.1.0"
description = "ETH Thesis Multimodal Learning Library"
authors = ["TheodorAmariucai <amariucaitheodor@protonmail.com>", "PyTorchMultimodalTeam torchmultimodal@fb.com"]
# https://github.com/amariucaitheodor/acquiring-linguistic-knowledge

[tool.poetry.dependencies]
python = "^3.10"
torch = "2.0.0"
wandb = "^0.15.2"
omegaconf = "^2.3.0"
pytorch-lightning = "^2.0.2"
transformers = "^4.29.1"
datasets = "^2.12.0"
hydra-core = "^1.3.2"
requests = "^2.30.0"
DALL-E = "^0.1"
pycocotools = "^2.0.6"
Pillow = "^9.5.0"
protobuf = "^4.23.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
