_target_: alkmi.definitions.AblationArguments

text_perc: 100
vision_perc: 0

training:
  _target_: alkmi.definitions.TrainingArguments
  lightning:
    max_steps: 450000
    accelerator: 'gpu'
    devices: 1 # -1 for all GPUs (if using more GPUs)
    val_check_interval: 200
    limit_val_batches: 200 # REQUIRED, otherwise the validation loop doesn't terminate
    precision: 16-mixed # 'bf16' not supported on either local or Euler GPU
    accumulate_grad_batches: 1
    num_sanity_val_steps: 0
    strategy: ddp
    enable_progress_bar: true
  lightning_checkpoint:
    dirpath: "./bert-debug"
    filename: bert-{epoch:02d}-{step}
  lightning_load_from_checkpoint: null
  seed: -1
  batch_size: 24
  num_workers: 1
  use_wandb: false
  # https://arxiv.org/pdf/1810.04805.pdf, A.2 Pre-training Procedure
  learning_rate: 1e-4
  adam_eps: 1e-6
  adam_weight_decay: 1e-2
  adam_betas: [ 0.9, 0.999 ]
  warmup_steps: 2000

datasets:
  _target_: alkmi.definitions.TrainingDatasetsInfo
  ablation:
    # For VLDataModule, column "image" either needs to have an image (not the case for "facebook/pmd", "wit"), or be missing
    _target_: alkmi.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: alkmi.definitions.HFDatasetInfo
        key: theodor1289/wit_mini
        split_key_mapping:
          validation: test # 'validation' split does not exist for wit
    val:
      - _target_: alkmi.definitions.HFDatasetInfo
        key: theodor1289/wit_mini
        split_key_mapping:
          validation: test # 'validation' split does not exist for wit
    datamodule_extra_kwargs: # This key is used in the MLMDataModule
      text_columns: [ "text" ]

model:
  _target_: alkmi.definitions.ModelArguments
  pretrained: null
  mlm_perc: 0.15
  name: bert
