program: train.py
name: flava-textvision-wit_mini-debug
description: Miniature FLAVA (fewer weights) text-vision sweep run on the WiT-mini (1k samples) dataset.
project: multimodal-wit_mini
run_cap: 100
entity: rycolab
method: bayes # uses probability of improvement (PI) to select the next hyperparameter configuration
metric:
  name: evaluation/pseudo_perplexity
  goal: minimize
command:
  - ${env}
  - ${interpreter}
  - -m
  - train
  - config=configs/debug.yaml
early_terminate:
  type: hyperband
  max_iter: 64
  s: 4
  eta: 2
parameters:
  accumulate_grad_batches:
    distribution: categorical
    values: [ 1, 4, 8, 16 ]
  warmup_steps:
    distribution: categorical
    values: [ 500, 2000 ]
  learning_rate:
    distribution: uniform
    min: 1e-4
    max: 1e-2