_target_: alkmi.definitions.AblationArguments

text_perc: 100
vision_perc: 100

training:
  _target_: alkmi.definitions.TrainingArguments
  lightning:
    max_steps: 450000
    accelerator: 'gpu'
    devices: 1 # -1 for all GPUs (if using more GPUs)
    val_check_interval: 8000
    limit_val_batches: 2000 # REQUIRED, otherwise the validation loop doesn't terminate
    precision: 16-mixed # 'bf16' not supported on either local or Euler GPU
    accumulate_grad_batches: 32
    num_sanity_val_steps: 0
    strategy: ddp_find_unused_parameters_true # ddp for BERT, RoBERTa
    enable_progress_bar: false
  lightning_checkpoint:
    dirpath: "/cluster/work/cotterell/tamariucai/HuggingfaceCheckpoints/flava-textvision/"
    filename: flava-{epoch:02d}-{step}
    save_last: true
    every_n_train_steps: 15000 # otherwise it occupies too much disk space
    save_on_train_epoch_end: true
    verbose: true
  lightning_load_from_checkpoint: null
  seed: -1
  batch_size: 15
  num_workers: 2
  learning_rate: 2e-4
  adam_eps: 1e-8
  adam_weight_decay: 1e-2
  adam_betas: [ 0.9, 0.999 ]
  warmup_steps: 2000
  use_wandb: true

datasets:
  _target_: alkmi.definitions.TrainingDatasetsInfo
  ablation:
    # For VLDataModule, column "image" either needs to have an image (not the case for "facebook/pmd", "wit"), or be missing
    _target_: alkmi.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: alkmi.definitions.HFDatasetInfo
        key: theodor1289/wit
        split_key_mapping:
          validation: test # 'validation' split does not exist for wit
    val:
      - _target_: alkmi.definitions.HFDatasetInfo
        key: theodor1289/wit
        split_key_mapping:
          validation: test # 'validation' split does not exist for wit
    datamodule_extra_kwargs: # This key is used in the MLMDataModule
      text_columns: [ "text" ]

model:
  _target_: alkmi.definitions.ModelArguments
  pretrained: null
  name: flava