program: train.py
name: flava-textvision-wit-sampling_temperature
description: Sweep search to find the best datamodule sampling temperature for FLAVA (text-vision) on the WiT dataset.
project: multimodal-wit
run_cap: 100
entity: rycolab
method: bayes # uses probability of improvement (PI) to select the next hyperparameter configuration
metric:
  name: evaluation/pseudo_perplexity
  goal: minimize
command:
  - ${env}
  - ${interpreter} # makes sure the right interpreter is used on Euler (3.10 req. for BLiMP)
  - -m
  - train
  - config=configs/wit.yaml
early_terminate: # We do want to early_terminate here because we're interested in the best configs.
  type: hyperband
  max_iter: 64
  s: 4
  eta: 2
parameters:
  sampling_temperature:
    distribution: uniform
    min: 0.0
    max: 1.0
  text_perc:
    distribution: categorical
    values: [ 1 ]
  vision_perc:
    distribution: categorical
    values: [ 100 ]
