program: train.py
name: flava-textvision-wit_medium-hyperparameters
description: Hyperparameter sweep search for FLAVA (text-vision) on the tiny WiT dataset.
project: alkmi-wit_medium
run_cap: 100
entity: rycolab
method: bayes # uses probability of improvement (PI) to select the next hyperparameter configuration
metric:
  name: evaluation/pseudo_perplexity
  goal: minimize
command:
  - ${env}
  - ${interpreter} # makes sure the right interpreter is used on Euler (3.10 req. for BLiMP)
  - -m
  - train
  - config=configs/wit_medium/wit_medium.yaml
parameters:
  accumulate_grad_batches:
    distribution: categorical
    values: [ 16, 32, 64 ]
  warmup_steps:
    distribution: categorical
    values: [ 2000, 10000 ]
  learning_rate:
    distribution: categorical
    values: [ 0.003, 0.002, 0.001 ]
  seed:
    distribution: categorical
    values: [ 1472111, 2550093, 5501650, 1930309, 7865220, 5974287, 7203693, 887373, 814622, 100000 ]
